const { server_error_code, success_code, conflict_code, resource_not_found, no_content, resource_created } = require('../config/constants');
const { getCourseByName, createCourse, updateCourse, getAllCourses, getCourseById, getCourseByFilter, getAllCoursesCount, getCourseByFilterCount } = require('../models/course.model');
const { sendError, ReS } = require('../services/generalHelper.service');

const createNewCourse = async (req, res) => {
    try {
        let courseData = req.body;
        const user = req.user
        courseData = { ...courseData, instructor_id: user.id }
        if ((await getCourseByName(courseData.name))) return sendError(res, conflict_code, 'Course already exists! ðŸ˜Š');
        await createCourse(courseData);
        return ReS(res, resource_created, 'ðŸ˜ŠHurry! Congratulation for your Successfully registered new course!')
    } catch (error) {
        return sendError(res, server_error_code, 'Internal Server Error!ðŸ˜ž')
    }
}

const updatePreviousCourse = async (req, res) => {
    try {
        const course_id = req.params.id
        const courseData = req.body;
        await updateCourse(course_id, courseData);
        return ReS(res, resource_created, 'ðŸ˜ŠCouse  data updated successfully! ')
    } catch (error) {
        return sendError(res, server_error_code, 'Internal Server Error!ðŸ˜ž')
    }
}
const getCourses = async (req, res) => {
    try {
        const page = req.query.page ? parseInt(req.query.page) : 1;
        const limit = 10;
        const offset = (page - 1) * limit;
        const courseData = await getAllCourses(limit, offset);
        if (!courseData.length) return sendError(res, resource_not_found, 'No course found Empty course list!ðŸ˜ž')
        const totalCourses = (await getAllCoursesCount()).total_count;
        const totalPages = Math.ceil(totalCourses / limit);
        return ReS(res, success_code, 'ðŸ˜ŠCourses are fetched successfully! ', { courses: courseData, page: totalPages, limit: 10 })
    } catch (error) {
        return sendError(res, server_error_code, 'Internal Server Error!ðŸ˜ž')
    }
}

const getCourse = async (req, res) => {
    try {
        const course_id = req.params.id
        const courseData = await getCourseById(course_id)
        if (!courseData) return sendError(res, resource_not_found, 'Course not found!ðŸ˜ž')
        return ReS(res, success_code, 'ðŸ˜ŠCourse are fetched successfully! ', { courseData })
    } catch (error) {
        return sendError(res, server_error_code, 'Internal Server Error!ðŸ˜ž')
    }
}

const getCouresByFilters = async (req, res) => {
    try {
        const { name, tag, category } = req.body;
        const page = req.query.page ? parseInt(req.query.page) : 1;
        const limit = 10;
        const offset = (page - 1) * limit;
        const courseData = await getCourseByFilter(name, tag, category, limit, offset)
        if (!courseData.length) return sendError(res, resource_not_found, 'No course found with these filters!ðŸ˜ž')
        const totalCourses = (await getCourseByFilterCount(name, tag, category)).total_count;
        const totalPages = Math.ceil(totalCourses / limit);
        return ReS(res, success_code, 'ðŸ˜ŠFiltered Courses are fetched successfully! ', { courses: courseData, page: totalPages, limit: 10 })

    } catch (error) {
        console.log(error);
        return sendError(res, server_error_code, 'Internal Server Error!ðŸ˜ž')
    }
}

const removeCourse = async (req, res) => {
    try {
        const course_id = req.params.id
        if (!(await getCourseById(course_id))) sendError(res, resource_not_found, 'No course found to remove!ðŸ˜ž')
        return ReS(res, no_content, 'ðŸ˜ŠHurry! Course is deleted successfully! ', { courseData })
    } catch (error) {
        return sendError(res, server_error_code, 'Internal Server Error!ðŸ˜ž')
    }
}

module.exports = {
    createNewCourse,
    updatePreviousCourse,
    getCourses,
    getCourse,
    getCouresByFilters,
    removeCourse
}